config/routes.rb
Rails.application.routes.draw do
  scope '/(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    devise_for :users, skip: [:sessions] do
      get '/admin' => 'devise/sessions#new', :as => :new_user_session
      post '/admin' => 'devise/sessions#create', :as => :user_session
    end
    root to: 'pages#index'
    resources :events do
      resources :event_subscribes
    end
    resources :event_subscribes
    resources :users, only: [:show]
    get 'pages/archive'
    get :search, to: 'events#search'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted"> Designed by Shtymak and Kolan4ick in 2021 </span>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
      <%= t("navbar.title") %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="<%= events_path %>"><%= t("navbar.events") %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= pages_archive_path %>"><%= t("navbar.archive") %></a>
        </li>
      </ul>
      <div class="form-inline my-2 my-lg-0">
        <%= form_tag search_path, :method => :get do%>
        <%= text_field_tag( :search, params[:search], placeholder: t("navbar.search.placeholder"), class: "" ) %>
        <%= select_tag :begin_date, options_for_select(('2021-01-01'.to_date..'2022-12-31'.to_date).to_a, @begin_date), class: 'custom-select',prompt: t("navbar.search.date.start") %>
        <%= select_tag :end_date, options_for_select(('2021-01-01'.to_date..'2022-12-31'.to_date).to_a, @end_date), class: 'custom-select',prompt: t("navbar.search.date.end") %>
        <%= select_tag :price_type, options_for_select([[t("navbar.search.type.paid"),true],[t("navbar.search.type.free"),false]], @price), class: 'custom-select', prompt: t("navbar.search.type.title") %>
        <%= submit_tag t("navbar.search.bt.title"), :class => "btn btn-secondary"%>
      <%end%>

    </div>
    <div class="form-inline my-2 my-lg-0" style="padding-left:10px">
      <% if !(user_signed_in?) %>
        <div type="button" id="123" data-bs-toggle="modal" data-bs-target=".sign_in" class="btn btn-secondary">
          <%= t("navbar.sign_in") %>
        </div>
        <div type="button" data-bs-toggle="modal" data-bs-target=".sign_up" class="btn btn-secondary">
          <%= t("navbar.sign_up") %>
        </div>
      <% end %>
      <%if user_signed_in?%>
      <% if current_user.nickname!=""%>
        <font size="5"><%= link_to current_user.nickname, current_user%></font>
        <%else%>
        <font size="5"><%= link_to current_user.email, current_user%></font>
        <%end%>
        <span class="text-dark"><%= link_to t("navbar.sign_out"), destroy_user_session_path, method: :delete, :class => 'btn btn-secondary' %></span>
      <% end %>
    </div>
    <div class="dropdown language" style="padding:5px 10px 0px 4px">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuLocale" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= t(get_locale).upcase %>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuLocale">
        <% I18n.available_locales.each do |locale| %>
        <%= link_to(t(locale).upcase, request.params.merge( locale: locale ), class: "dropdown-item") if locale.to_s != get_locale.to_s %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_photo_form.html.erb
<div class="modal" id="imageModal" onclick="this.style.display='none'">
  <span class="button hover-red xlarge display-topright">&times;</span>
  <div class="modal-dialog modal-dialog-centered modal-lg">
      <img id="imgInImageModal" align="center" width="100%" height="100%">
  </div>
</div>

app/views/shared/_sign_in_form.html.erb
<div class="modal fade sign_in" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t("views.modals.sign_in.title") %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" align="center">
        <div class="errors_sign_in"></div>
        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), remote: true) do |f| %>
        <div class="form-inputs">
          <%= f.input :email, label:false, placeholder: t("views.modals.sign_in.email"), autofocus: true, input_html: { autocomplete: "email" } %>
          <%= f.input :password, label:false, placeholder: t("views.modals.sign_in.password"), input_html: { autocomplete: "current-password" } %>
          <%= f.input :remember_me, as: :boolean, label:t("views.modals.sign_in.remember_me") if devise_mapping.rememberable?%>
        </div>
        <div class="modal-footer">
          <%= f.button :submit, t("views.modals.sign_in.button.log_in"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/shared/_sign_up_form.html.erb
<div class="modal fade sign_up" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t("views.modals.sign_up.title") %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" align="center">
        <div class="errors_sign_up"></div>
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), remote: true) do |f| %>
        <div class="form-inputs">
          <%= f.input :email, required: true, label:false, placeholder: t("views.modals.sign_up.email"), autofocus: true, input_html: { autocomplete: "email" } %>
          <%= f.input :nickname, required: true, label:false, placeholder: t("views.modals.sign_up.nickname"), autofocus: true, input_html: { autocomplete: "nickname" } %>
          <%= f.input :phone, required: true, label:false, placeholder: t("views.modals.sign_up.phone"), autofocus: true, input_html: { autocomplete: "nickname" } %>
          <%= f.input :password, required: true, label:false, placeholder: t("views.modals.sign_up.password"), input_html: { autocomplete: "new-password" } %>
          <%= f.input :password_confirmation, required: true, label:false, placeholder: t("views.modals.sign_up.password_confirmation"), input_html: { autocomplete: "new-password" } %>
      </div>
      <div class="modal-footer">
        <%= f.button :submit, t("views.modals.sign_up.button.register"), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>