config/routes.rb
Rails.application.routes.draw do
  scope '/(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
    devise_for :users, skip: [:sessions] do
      get '/admin' => 'devise/sessions#new', :as => :new_user_session
      post '/admin' => 'devise/sessions#create', :as => :user_session
    end
    root to: 'pages#index'
    resources :events do
      resources :event_subscribes
    end
    resources :event_subscribes
    resources :users, only: [:show]
    get 'pages/archive'
    get :search, to: 'events#search'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :avatar
  has_many_attached :images
  has_many :event_subscribes
  has_many :users, :through => :event_subscribes

  def set_image=(src)
    file = File.open(Rails.root.join("public/seed_img/#{src}"))
    avatar.attach(io: file, filename: name)
  rescue OpenURI::HTTPError => e
    pp e
  end

  def photos=(objects)
    objects.each do |object|
      images.attach(io: object.open, filename: object.original_filename)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.where('end_date >= ?',Time.now).page(params[:page]).per($PERPAGE).with_attached_images
  end

  def show
      event
  end
  def search
    @search = params[:search]
    type_filter
    data_filter
    @events = @events.where("place LIKE '%#{params[:search]}%'").page(params[:page]).per($PERPAGE).with_attached_images
  end
  private

  def type_filter
    @price = params[:price_type]
    if @price ==""
      @events = Event.all
    else
        @events =Event.where(price: @price )
    end
  end

def data_filter
  @end_date = params[:end_date]
  @begin_date = params[:begin_date]
  if @begin_date != '' || @end_date != ''
  @events = @events.where('end_date <= ? AND begin_date >= ?', @end_date.to_date, @begin_date.to_date)
else
  @events = @events.order(:name).page(params[:page]).per($PERPAGE).with_attached_images
end
end
  def event
      @event ||= Event.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_image(image, width = 250, height = 250, clas = '')
    image_tag (image.attached? ? image : '/nfd.jpg'), width: width, height: height, class: clas
  end

end

app/views/events/_event.html.erb
<div class="col-12 col-md-5 col-lg-4">
  <div class="" style="w-100 order-3 d-flex justify-content-end">
    <%= link_to event_path(event) do %>
  <style> img {
   padding:1px;
   border:5px solid #212529;
   background-color:#6c757d;
}
</style>
    <%= event_image(event.avatar, 250, 250, "rounded-circle")%>
    <div class="card-body" align="left">
      <%= event.name%>
    </div>
  <%end%>
</div>
</div>

app/views/events/index.html.erb
<h1><%=t("index.title")%></h1>
  <div class="row m-3">
    <%=render @events%>
  </div>

<%=paginate @events%>

app/views/events/search.html.erb
<h1>Search</h1>
<div class="row">
  <%=render @events%>
</div>
<%=paginate @events%>

app/views/events/show.html.erb
<script>
  function onClickImage(element) {
    document.getElementById("imgInImageModal").src = element.src;
    document.getElementById("imageModal").style.display = "block";
  }
</script>
<div class="m-3">
  <style>
    .w3-border {
      border: 3px solid #212529;
    }
    .w3-container,
    .w3-panel {
      padding: 0.01em 16px;
    }
    .w3-round-xlarge {
      border-radius: 16px;
    }
  </style>
  <div class="w3-container w3-border w3-round-xlarge">
    <h1>
      <%= t("views.events.show.name") %>
      <%=@event.name%>
    </h1>
  </div>
  <div>
    <br>
      <style>
        img {
          padding: 1px;
          border: 5px solid #212529;
          background-color: #6c757d;
          float: left;
          margin: -1vw 2vw 17px 0;
        }
      </style>
      <div type="button">
        <%= image_tag @event.avatar, width:300, height:300, onclick:"onClickImage(this)", class:"rounded-circle" %>
      </div>
      <font size="6" color="" face="Tahoma">

        <%=t("views.events.show.orgranizator")%>
        <%= @event.orgranizator%>
        <br>
        <%= t("views.events.show.place") %>
        <%=@event.place%>
        <br>
        <%=t("views.events.show.type.title")%>
        <%if @event.price%>
          <%=t("views.events.show.type.true")%>
        <%else%>
          <%=t("views.events.show.type.false")%>
        <%end%>
        <br>
        <%= t("views.events.show.begin_date") %>
        <%=@event.begin_date.to_date.day%>.<%=@event.begin_date.to_date.month%>.<%=@event.begin_date.to_date.year%>
        <br>
        <%= t("views.events.show.end_date") %>
        <%=@event.end_date.to_date.day%>.<%=@event.end_date.to_date.month%>.<%=@event.end_date.to_date.year%>
        <br>
        <%= t("views.events.show.count")%>
        <%= @event.event_subscribes.size%>
      </font>
    </div>
    <div class="body">
      <br>
      <h4>
        <%= t("views.events.show.body")%>
        <%= @event.body%>
      </h4>
    </div>
    <h4><%= t("views.events.show.images") if @event.images.count>0%></h4>
    <br>
    <div class="col-9">
      <%@event.images.each do |image|%>
        <div type="button" class="photo_link">
          <%=image_tag image, width:250, height:250, onclick:"onClickImage(this)"%>
        </div>
      <%end%>
    </div>
    <% if @event.end_date >= Time.now %>
      <% if user_signed_in? %>
        <% pre_event = @event.event_subscribes.find { |eventsub| eventsub.user_id == current_user.id && eventsub.event_id == @event.id} %>
          <% if pre_event %>
            <%= button_to t("views.events.show.button.unsubscribe"), event_event_subscribe_path(@event, pre_event), class:"btn btn-danger", method: :delete %>
          <% else %>
            <%= button_to t("views.events.show.button.subscribe"), event_event_subscribes_path(@event), class:"btn btn-success", method: :post %>
          <% end %>
        <% else %>
          <h4 class"p-2"="class" p-2""="p-2" ""><%= t("views.events.show.tip") %>
            <a href="" data-bs-toggle="modal" data-bs-target=".sign_in">
              <%= t("views.events.show.button.sign_in") %>
            </a>
            <%= t("views.events.show.tipor") %>
            <a href="" data-bs-toggle="modal" data-bs-target=".sign_up">
              <%= t("views.events.show.button.sign_up") %>
            </a>
          <% end %>
        <% end %>
      </div>